# Generated by Django 4.0.5 on 2022-06-21 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
